### ISSUE TITLE
implement Serialize / Deserialize for ast nodes

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#230]
It's necessary for plugin system.

# TODOs
 - [x] implement Serialize / Deserialize for Span
Currently span holds byte position, but to support EsTree spec, we should change it to hold line, column instead of it.

 - [x] implement Serialize for ast nodes.
 - [ ] implement Deserialize for ast nodes.
It requires lots of work.

**Comment by kdy1** [comment]
I have an idea to reduce work.


We introduce some new proc macros.

## trait `AstNode`
Trait `AstNode` is updated to have an associated constant `TYPE`.
```rust
/// A trait for ast nodes.
pub trait AstNode: Debug + PartialEq + Clone + Spanned {
    /// Used when serialized
    const TYPE: &'static str;
}
```


## `#[ast_node(type = "Foo")]`
Our `#[ast_node]` macro is changed to accept parameter `type` and implements `swc_common::AstNode`, `Serialize` and `Deserialize` for the type.


## `impl_deserialize_typed!`
`impl_deserialize_typed` macros accepts list of types (where all of them implements `AstNode`).
 works by deserializing json's type field first and
