### ISSUE TITLE
Performance bugs with known fixes

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#2370]
### general

 - [ ] Dynamic linking of iconv

 - [ ] Dynamic linking of libresolv

 - [x] Use `ahash` #2384()

### `swc_atoms`

 - [x] Switch to parking_lot (https://github.com/swc-project/swc/pull/2411)

Related: https://github.com/servo/string-cache/issues/242

 - [ ] Thread-local interning, in cost of more memory use while `LocalInterner` is alive.

### `swc_common`

 - [ ] Global / Local pool for `Mark` allocation.

This will result in a huge difference as `Mark` is used for various purposes.

### `swc_ecma_ast`

 - [ ] Methods of `IdentLike` can be optimized.

Comparison of `js_word` is much faster than string comparison.

### `swc_ecma_parser`

 - [ ] Skip typescript types, without storing them.

 - [x] Optimize `parse_block` (#2406)

We should create a vector with good initial capacity.

 - [ ] Optimize parsing of expressions. (#2437)

We perform too much backtracking.

### `swc_ecma_codegen`

 - [ ] Don't allocate while print a number.

 - [ ] Use faster library like `ryu` for printing numbers.

### `swc_ecma_transforms_base`

 - [x] `resolver`: Use better way to fetch parent `Mark`. (#2392)

It uses `Mark::parent` but it's very slow operation.
This also shows up in the profile result, as `Mark::parent()` involves a global lock.

 - [ ] `hygiene`: Reduce allocation of `JsWord`

Creating a `JsWord` requires locking global interner.

### `swc_ecma_utils`

 - [x] Parallel `collect_decls`. (#2394)

It's easy to parallelize it.

### `swc_ecma_transforms_base`

 - [ ] Use single `Mutex` instead of lots of `AtomicBool`s for helper.

### `swc_ecma_transforms_macros`

 - [x]  `#[fast_path]` has exponential time complexity. (#2439)

### `swc_ecma_transforms_compat`

 - [ ] `destructuring` visits nodes for exponential times.

 - [ ] `for_of` visits nodes for exponential times.

 - [ ] `object_rest` has exponential time complexity.

 - [x] `async_to_generator` visits nodes for exponential times. (#2442)

These are simple, but I postponed because of #2441.

---

`Fold` results in a lot of `memmove`. So transforms in `@swc/core` should use `VisitMut` instead of `Fold`.

The order of tasks is ordered by real-world data.
The sooner it comes, the higher effect it has.

 - [x] Migrate `es2015::parameters` (#2804)
 - [x] Migrate `es2015::block_scoping`(#2817)
 - [x] Migrate `es2015::desturcturing` (#2947)
 - [x] Migrate `es2015::arrow`
 - [x] Migrate `es2015::computed_props` (#2857)
 - [x] Migrate `es2015::shorthand`
 - [x] Migrate `es2015::for_of`
 - [x] Migrate `es2015::block_scoped_fn`
 - [x] Migrage `es2015::regenerator` (#3007 / #3037)
 - [x] Migrate `es2015::classes` (#2995 / #3020)
 - [x] Migrate `es2015::spread` (#2888)
 - [x] Migrate `es2020::class_properties` (#2966 / #2993)
 - [x] Migrate `es2020::opt_chaining` (#2891)
 - [x] Migrate `es2020::nullish_coalescing` (#2442)
 - [x] Migrate `es2020::export_namespace_from`(#2751)
 - [x] Migrate `es2017::async_to_generator` (#2709)
 - [x] Migrate `es2018::object_rest_spread` (#2997)
 - [x] Migrate `es2019::optional_catch_bindings`
 - [x] Migrate `es2016::exponentation`

### `swc_ecma_transforms_optimization`

 - [x] `dce`: Parallel tree shaking. (#2384)

`Arc` can be used to share data from analysis.

 - [ ] `dce`: Parallel analyzer.

It seems like a simple task, but we have to consider the time used for hashing.

### `swc_bundler`

 - [ ] Don't clone modules if there's only one entry.

https://github.com/swc-project/swc/blob/656f3e944df7ec8d9f1ab7ac2745c0d4dde3e605/bundler/src/bundler/chunk/merge.rs#L157-L168

 - [x] Make `inline` pass parallel. (#2394)

 - [ ] Make `keyword renaming` pass parallel.

 - [ ] Add options to remove exports.

 - [x] Make dropping of bundler parallel (#2406)

### `swc_node_bundler` (`swcpack`)

 - [ ] Drop bundler in other thread.

**Comment by kwonoj** [comment]
I've marked few visit_mut refactorings as done, and trying to make some more changes.
