### ISSUE TITLE
Performant ES identifier management

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#2831]
# Motivation

While working to improve the performance of name mangler, I found that `esbuild` performs renaming from multiple parts instead of doing so from a single module, like `swc_ecma_minifier` or `swc_ecma_transforms_base::hygiene`, and it's important for performance.

For every part of `swc`, I always selected reusability over performance. And of course, this feature can be implemented as a reusable feature, but I'm going to select performance this time because the renaming is the last pass anyway.

# Changes

To improve performance, bundler API and code generator API should be modified. These will be implemented as generic and will be noop if you are not using the name mangler.

## `swc_ecma_codegen`

 - [ ] Use renamer from code generator.

This includes 

 - `hygiene` pass
 - name mangler

This will avoid useless string interning, which involves a global lock and lots of allocations.

 - [ ] Generate code in parallel

This requires some API changes. I'm not sure about this at the moment.

## `swc_bundler`

 - [ ] Make name analysis parallel.

Bundler can use some information to make renaming parallel.

https://github.com/evanw/esbuild/blob/91b8a21440682ce7dc90b79f5fa10315b23b624e/internal/bundler/linker.go#L4137-L4218
