### ISSUE TITLE
[Meta] Known performance issues of minifier

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#3516]
### General

 - [x] Reduce call to `span()`, especially if an optimizer function does not work. (https://github.com/swc-project/swc/pull/3512)

### `SimplifyExpr`

 - [ ] Reduce `memmove`

We should not use `map_with_mut`

### `analyze`

 - [ ] Make it parallel or use single hashmap for children

### `Optimizer`

Some items show up in the profiling result.

 - [ ] Move `join_vars` to the pure (parllel) optimizer

 - [ ] Move `compress_if_stmt_as_cond` to the pure optimizer.

 - [ ] Move `make_sequences` to the pure optimizer

 - [ ] Move `eval_numbers` to the pure optimizer

**Comment by kdy1** [comment]
Merged into #3639
