### ISSUE TITLE
Revamp before v1.1

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#376]
Plugin system is implemented, so swc is facing v1.1 release.
I want to solve some issues before releasing v1.1.

## TODOs
 - [ ] (maybe) improve parser performance (by using look up table)
 - [x] reduce binary size (#157)
 - [x] improve serialization performance
Especially, I'll going to read some articles about V8's hidden class. It might boost serialization significantly. If hidden class is not supported for object constructed from native code, I'll try to boost serialization performance by using `JSON.parse`

 - [x] allow using tsx with ts, jsx (#213)
This is currently possible with swc-loader, but it's not possible without it.

 - [x] fix source map support (#349)
This is very important

 - [x] implement comment support (while using plugin)

(maybe) means I may postpone task.

<details>
    <summary>swc benchmark (with noop plugin)</summary>

[transform]
  swc (es3) x 676 ops/sec ±1.31% (83 runs sampled)
  swc (es5) x 733 ops/sec ±1.02% (88 runs sampled)
  swc (es2015) x 734 ops/sec ±1.18% (88 runs sampled)
  swc (es2016) x 1,586 ops/sec ±3.92% (73 runs sampled)
  swc (es2017) x 1,437 ops/sec ±7.05% (85 runs sampled)
  swc (es2018) x 1,828 ops/sec ±13.75% (81 runs sampled)
  swc (plugin, es3) x 203 ops/sec ±0.52% (81 runs sampled)
  swc (plugin, es5) x 210 ops/sec ±0.25% (83 runs sampled)
  swc (plugin, es2015) x 205 ops/sec ±2.36% (82 runs sampled)
  swc (plugin, es2016) x 475 ops/sec ±0.47% (87 runs sampled)
  swc (plugin, es2017) x 466 ops/sec ±0.38% (86 runs sampled)
  swc (plugin, es2018) x 607 ops/sec ±25.64% (77 runs sampled)
  swc (optimize, es3) x 582 ops/sec ±0.60% (88 runs sampled)
  swc (optimize, es5) x 623 ops/sec ±0.81% (87 runs sampled)
  swc (optimize, es2015) x 614 ops/sec ±2.05% (84 runs sampled)
  swc (optimize, es2016) x 1,398 ops/sec ±0.36% (90 runs sampled)
  swc (optimize, es2017) x 1,358 ops/sec ±0.32% (89 runs sampled)
  swc (optimize, es2018) x 1,517 ops/sec ±1.18% (86 runs sampled)
  babel (es5) x 42.60 ops/sec ±6.41% (56 runs sampled)
</details>
