### ISSUE TITLE
Roadmap (huge refactorings)

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#8074]
```[tasklist]
### Tasks
- [ ] https://github.com/swc-project/swc/issues/8078
- [ ] Make parser faster by using `TokenKind`
- [ ] https://github.com/swc-project/swc/issues/8026
- [x] Split `swc_ecma_transforms_compat` into multiple crates
```

**Comment by kdy1** [comment]
Closing as done. I'll try rewriting parser from scratch.
