### ISSUE TITLE
CSS/HTML/XML parser must use AtomStore API

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#8234]
I made a mistake.

https://github.com/swc-project/swc/issues/4946#issuecomment-1798052358

https://rustdoc.swc.rs/swc_atoms/struct.AtomStore.html

```[tasklist]
### Tasks
- [ ] https://github.com/swc-project/swc/issues/8237
- [ ] https://github.com/swc-project/swc/issues/8236
- [ ] https://github.com/swc-project/swc/issues/8235
```

**Comment by kdy1** [comment]
Closing as default api is fast enough
