### ISSUE TITLE
Migrate to stable rustc

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#883]
# Tasks

 - [x] `Visit` / `Fold` for stable rustc
 - [x] `VisitWith` / `FoldWth` for stable rustc
   - [x] visit_with / fold_with
   - [x] visit_children / fold_children
 - [x] `Visit` / `Fold` for `Either`
 - [x] `Fold` for `Repeat`
 - [x] chain!
 - [x] Migrattion
   - [x] swc_visit

   - [x] swc_ecma_transforms
     - [x] 1. specialization
     - [x] 2. fix regressions
     - [x] 3. box_syntax
     - [x] 4. box_patterns

**Comment by kdy1** [comment]
@ry @bartlomieju I can add a feature to visitor generator which creates a special visitor that visits children a provided visitor. Will it help deno_lint?

**Comment by bartlomieju** [comment]
> @ry @bartlomieju I can add a feature to visitor generator which creates a special visitor that visits children a provided visitor. Will it help deno_lint?

It's not really required at the moment but it surely be useful

**Comment by divy-work** [comment]
Thanks! Migrating to stable rust might fix https://github.com/nestdotland/deno_swc/pull/14
