### ISSUE TITLE
Ideas for `swc_alloactor`

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9253]
```[tasklist]
### Tasks
- [ ] (Maybe) Change `Allocator.scope` to an unsafe function.
- [ ] Transmute at https://github.com/swc-project/swc/blob/d2e96bf40f6cfe60b7b1d7ef3b77efacebaad675/crates/swc_allocator/src/alloc.rs#L36-L39 is not safe
- [ ] Run miri
- [ ] Assertions to check escape from arenas (We need both of `feature = "debug"` and `cfg!(debug_assertions)`).
- [ ] Change scope API to RAII
```
