### ISSUE TITLE
Known performance issues

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#9601]
```[tasklist]
### Tasks (`oxc`)
- [ ] https://github.com/swc-project/swc/pull/9602
- [ ] https://github.com/swc-project/swc/pull/9680
- [ ] For esnext + typescript/ react-dev, resolver / hygiene / fixer is way too much overhead.
- [ ] https://github.com/swc-project/swc/issues/9603
- [ ] https://github.com/swc-project/swc/pull/9696
- [ ] https://github.com/swc-project/swc/pull/9613
```

```[tasklist]
### Tasks (`rspack`)
- [ ] lints are too slow
- [ ] https://github.com/swc-project/swc/pull/9689
- [ ] https://github.com/swc-project/swc/pull/9683
- [ ] codegen is too slow because of the string copy operation
- [ ] https://github.com/swc-project/swc/pull/9697
- [ ] https://github.com/swc-project/swc/issues/9703
```

**Comment by levi-nz** [comment]
Does this mean `chain!` will be removed entirely?

**Comment by kdy1** [comment]
I think we should. It seems like it's misdesigned.

**Comment by levi-nz** [comment]
If I understand it correctly, it simply visits with `A` then `B`, so same as `visit_with(A); visit_with(B)`. I think we should make it combine all visitors together and visit in one pass or just remove it. This might work for some existing visitors but I'm not sure. If it does, it would probably optimize said visitors.

**Comment by kdy1** [comment]
In the profiling result, `visit_with(noop())` was not a noop. That's why I think it's misdesigned.

**Comment by kdy1** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/09838dcd-55b8-43ba-9953-9b2ce075ab01">

Performance profiling result for a large file.

**Comment by kdy1** [comment]
Renaming pass and block_scoping pass is too slow.
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/1aca96af-844f-4ea9-8b6a-7e51c212d67e">

**Comment by kdy1** [comment]
Slow functions: 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7f6ec24a-14b8-4075-8959-d3ecd3fc10d7">

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
